s=set()
s.add(input("Enter number 1 : "))
s.add(input("Enter number 2 : "))
s.add(input("Enter number 3 : "))
s.add(input("Enter number 4 : "))
s.add(input("Enter number 5 : "))
s.add(input("Enter number 6 : ")) 
print(s)
print(len(s))